{
 "title": "Collectd System view",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "$prefix.*" },
   { "name": "prefix", "query": "collectd.com.dataiku" }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(sumSeriesWithWildcards($prefix.$host.cpu.[0-128].percent.{user,system,guest,steal}, 7), 5), 3)"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards($prefix.$host.memory.percent.used, 6), 3)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards($prefix.$host.interface.*.if_octets.rx, 5), 3, 6)"
    },
    {
     "target": "aliasByNode(sumSeriesWithWildcards($prefix.$host.interface.*.if_octets.tx, 5), 3, 6)"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$host.df.*.percent_bytes.used, 3, 5)"
    }
   ]
  },
  {
   "title": "RAM Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(collectd.com.dataiku.$host.memory.memory.{used,buffered,cached}, 6),  3)"
    }
   ]
  },
  {
   "title": "Disk I/O latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode($prefix.$host.disk.{m,s,xv}d[a-z].disk_io_time.weighted_io_time, 3, 5)"
    }
   ]
  }
 ]
}