{
 "title": "Dataiku DSS - System view",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "dss.*" }
  ]
 },
 "panels": [
  {
   "title": "Average CPU usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(averageSeriesWithWildcards(sumSeriesWithWildcards(dss.$host.collectd.cpu.[0-128].{user,system,guest,steal}, 5), 4), 1)"
    },
    {
     "target": "aliasByNode(averageSeriesWithWildcards(sumSeriesWithWildcards(dss.$host.collectd.cpu.[0-128].percent.{user,system,guest,steal}, 6), 4), 1)"
    }
   ]
  },
  {
   "title": "RAM Usage (%)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(dss.$host.collectd.memory.percent.{used,buffered,cached}, 5), 1)"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(dss.$host.collectd.interface.*.if_octets.rx, 4), 1, 4, 5)"
    },
    {
     "target": "aliasByNode(sumSeriesWithWildcards(dss.$host.collectd.interface.*.if_octets.tx, 4), 1, 4, 5)"
    }
   ]
  },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.collectd.df.*.df_complex.used, 1, 4)"
    }
   ]
  },
  {
   "title": "RAM Usage (bytes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(dss.$host.collectd.memory.{used,buffered,cached}, 4),  1)"
    }
   ]
  },
  {
   "title": "Disk I/O latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "target": "aliasByNode(sumSeriesWithWildcards(dss.$host.collectd.disk.*.disk_io_time.weighted_io_time, 4), 1)"
    }
   ]
  }
 ]
}