{
 "title": "Dataiku DSS - Backend view",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "dss.*" }
  ]
 },
 "panels": [
  {
   "title": "Active users",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.backend.server.dku.collaboration.activeUsers, 1)"
    }
   ]
  },
  {
   "title": "Nb datasets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.backend.server.catalog.indexAll.datasets.count, 1)"
    }
   ]
  },
  {
   "title": "Nb recipes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.backend.server.catalog.indexAll.recipes, 1)"
    }
   ]
  },
  {
   "title": "Nb jobs",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.collectd.processes.dss_fek.ps_count.processes, 1, 4)"
    },
    {
     "target": "aliasByNode(dss.$host.collectd.processes.dss_jek.ps_count.processes, 1, 4)"
    }
   ]
  },
  {
   "title": "Backend java heap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.backend.server.jvm.memory.heap.used, 1)"
    }
   ]
  },
  {
   "title": "Backend open files",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "target": "aliasByNode(dss.$host.collectd.processes.dss_backend.file_handles.mapped, 1)"
    }
   ]
  }
 ]
}